config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  resources :flights
  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers, dependent: :delete_all
  belongs_to :flight

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings, dependent: :delete_all

  belongs_to :arrival_airport, class_name: 'Airport'
  belongs_to :departure_airport, class_name: 'Airport'

  

  def route
    { arrival: arrival_airport, departure: departure_airport }
  end

  def passenger_count
    bookings.map(&:passengers_count).sum
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, counter_cache: true

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @booking.flight = Flight.find(new_params[:flight_id])

    new_params[:number_of_passengers].times { @booking.passengers.build }
  end

  def create
    @flight = Flight.find(params[:booking][:flight_id])
    @booking = @flight.bookings.build(create_params)

    if @booking.save
      @booking.send_confirmation
      render :show
    else
      flash[:error] = 'Failed Booking flight'
      render :new
    end
  end

  private

  def create_params
    params.require(:booking)
          .permit(passengers_attributes: %i[name email])
  end

  def new_params
    params.require(:booking)
          .permit(:flight_id, :number_of_passengers)
          .transform_values(&:to_i)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    @filters = store_filters
    @number_of_passengers = search_params[:number_of_passengers]

    filter_flights unless search_params.empty?
  end

  private

  def search_params
    if params[:filter]
      params.require(:filter)
            .permit(:departure_airport_id, :arrival_airport_id, :number_of_passengers, start: %i[year month day])
            .compact_blank
    else
      {}
    end
  end

  def filter_flights
    # got the idea here https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/
    search_params.each do |k, v|
      case k
      when 'start'
        filter_flight_dates(v.compact_blank)
      when 'number_of_passengers'
        nil
      else
        @flights = @flights.where(k => v)
      end
    end
  end

  def filter_flight_dates(date)
    date.each do |time_unit, time|
      start_date = case time_unit
                   when 'year' then DateTime.new(time.to_i)
                   when 'month' then DateTime.new(search_params[:start][:year].to_i, search_params[:start][:month].to_i)
                   when 'day' 
                    if params[:filter][:start][:month] == ''
                      DateTime.new(search_params[:start][:year].to_i)
                    else
                      DateTime.new(search_params[:start][:year].to_i, search_params[:start][:month].to_i, time.to_i)
                    end
                   end

      end_date = case time_unit
                 when 'year' then start_date.end_of_year
                 when 'month' then start_date.end_of_month
                 when 'day' 
                  if params[:filter][:start][:month] == ''
                    start_date.end_of_year
                  else
                    start_date.end_of_day
                  end
                 end

      @flights = @flights.where('start >= ? AND start <= ?', start_date, end_date)
    end
  end

  def store_filters
    {
      departure_airport: has_filters? && params[:filter][:departure_airport_id],
      arrival_airport: has_filters? && params[:filter][:arrival_airport_id],
      number_of_passengers: has_filters? && params[:filter][:number_of_passengers],
      year: has_filters? && params[:filter][:start][:year],
      month: has_filters? && params[:filter][:start][:month],
      day: has_filters? && params[:filter][:start][:day]
    }
  end

  def has_filters?
    !params[:filter].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<% flash.each do |type, msg| %>
  <div> 
    <%= msg %>
  </div>
<% end %>

<h1>Booking</h1>

<div>
  <p> <strong>Start: </strong><%= @booking.flight.start.strftime("%l:%M %p; %e %B, %Y") %></p>
  <p> <strong>Duration: </strong><%= @booking.flight.duration_m %> minutes</p>
  <p> <strong>Route: </strong><%= "#{@booking.flight.route[:departure].code} - #{@booking.flight.route[:arrival].code}" %></p>
  <p> <strong>Number of passengers: </strong><%= @booking.flight.passenger_count %></p>
</div>

<%= form_with model: @booking do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Passengers</h3>
  <%= form.hidden_field :flight_id, value: @booking.flight.id %>
  <%= form.fields_for :passengers do |passengers_form| %>
    <p>
      <%= passengers_form.label :name %>
      <%= passengers_form.text_field :name %>
      <%= passengers_form.label :email %>
      <%= passengers_form.email_field :email %>
      <br>
    <p>
  <% end %>
  <%= form.submit "Submit" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking <%= @booking.id %></h1>

<div>
  <h3> Flight Info </h3>
  <div>
    <p> <strong>Start: </strong><%= @flight.start.strftime("%l:%M %p; %e %B, %Y") %></p>
    <p> <strong>Duration: </strong><%= @flight.duration_m %> minutes</p>
    <p> <strong>Route: </strong><%= "#{@flight.route[:departure].code} - #{@flight.route[:arrival].code}" %></p>
    <p> <strong>Number of passengers in flight: </strong><%= @flight.passenger_count %></p>
  </div>
</div>

<div>
  <h3> Booking Info </h3>
  <div>
    <% @booking.passengers.each do |passenger| %>
      <p> <span><%= passenger.name %></span> <i><%= passenger.email %></i>
    <% end %>
  </div>
</div>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_with scope: :filter, url: root_path, method: :get do |form| %>
  <%= form.collection_select :departure_airport_id, Airport.all, ->(airport){ airport.id }, ->(airport){ airport.code }, 
                             include_blank: "Departure Airport", 
                             selected: @filters[:departure_airport] %>
  <%= form.collection_select :arrival_airport_id, Airport.all, ->(airport){ airport.id }, ->(airport){ airport.code }, 
                             include_blank: "Arrival Airport",
                             selected: @filters[:arrival_airport] %>
  <!-- not a filter -->                          
  <%= form.select :number_of_passengers, [*1..4], prompt: "Number of Passengers",
                  selected: @filters[:number_of_passengers] %>
  <%= select_year Date.today, options = {start_year: Date.today.years_ago(1).year, end_year: 5.months.from_now.year, prefix: 'filter[start]'}, 
                  selected: @filters[:year] %>
  <%= select_month 0, prompt: 'Choose Month', prefix: 'filter[start]',
                   selected: @filters[:month] %>
  <%= select_day 0, prompt: 'Choose Day', prefix: 'filter[start]',
                 selected: @filters[:day] %>
  <%= form.submit "Search" %>
  <%= link_to "Clear Form", root_path %>
<% end %>

<% if @flights.empty? %>
  <br>
  <i><small> No flights available </small></i>
<% else %>
  <%= form_with scope: :booking, url: new_booking_path, method: :get do |f| %>
    <% @flights.each do |flight| %>
      <% 
        route = flight.route.transform_values { |v| v.code } 
        id = flight.id 
        start = flight.start.strftime("%e %B, %Y;  %l:%M %p")
      %>
      <%= f.radio_button :flight_id, id %>
      <%= f.label "flight_id#{id}", "#{route[:departure]}-#{route[:arrival]} #{start}" %> <br>
    <% end %>
    <%= f.hidden_field :number_of_passengers, value: @number_of_passengers %>
    <%= f.submit "Book Flight"%>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>